on:
  workflow_dispatch:
  push:
    branches: ["main"]
jobs:
  zap_scan:
    runs-on: ubuntu-latest
    name: Scan the web application
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          ref: main
      - name: ZAP API Scan
        uses: zaproxy/action-api-scan@v0.7.0
        with:
          docker_name: 'ghcr.io/zaproxy/zaproxy:stable'
          target: 'https://www.zaproxy.org'
          rules_file_name: .github/zap.ignore
          cmd_options: '-a'
      - name: publish test results
        uses: actions/upload-artifact@v1
        with:
          name: zap report
          path: ./zap_baseline_report.html
