on:
  workflow_dispatch:
  push:
     branches: ["main"]
jobs:
  zap_scan:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    name: Scan the webapplication
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          ref: main
      - name: ZAP Scan
        uses: zaproxy/action-baseline@v0.12.0
        with:
          docker_name: 'ghcr.io/zaproxy/zaproxy:stable'
          target: 'https://www.zaproxy.org'
          cmd_options: '-a'
