'on':
  - push
jobs:
  zap_scan:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    name: Scan the webapplication
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          ref: main
      - name: ZAP Scan
        uses: zaproxy/action-full-scan@v0.10.0
        with:
          docker_name: 'ghcr.io/zaproxy/zaproxy:stable'
          target: 'http://testphp.vulnweb.com/'
          # rules_file_name: .zap/rules.tsv
          cmd_options: '-a'
      - name: Archive protection artifacts
        uses: action/upload-artifact@v2
        with:
          name: zap report
          path: |
            ./zap_baseline_report.html
